import '../../enum/converter.dart';

/// The conversion factor to base unit of each `ConversionType`.
final Map<Converter, Map<dynamic, double>> conversionFactors = {
  Converter.acceleration: <dynamic, double>{},
  Converter.area: <dynamic, double>{},
  Converter.bloodCholesterol: <dynamic, double>{},
  Converter.bloodGlucose: <dynamic, double>{},
  Converter.capacitance: <dynamic, double>{},
  Converter.data: <dynamic, double>{},
  Converter.dataRate: <dynamic, double>{},
  Converter.density: <dynamic, double>{},
  Converter.dynamicViscocity: <dynamic, double>{},
  Converter.electricCharge: <dynamic, double>{},
  Converter.electricCurrent: <dynamic, double>{},
  Converter.electricPotential: <dynamic, double>{},
  Converter.electricalConductance: <dynamic, double>{},
  Converter.electricalResistance: <dynamic, double>{},
  Converter.energy: <dynamic, double>{},
  Converter.force: <dynamic, double>{},
  Converter.frequency: <dynamic, double>{},
  Converter.illuminance: <dynamic, double>{},
  Converter.inductance: <dynamic, double>{},
  Converter.kinematicViscocity: <dynamic, double>{},
  Converter.length: <dynamic, double>{},
  Converter.luminance: <dynamic, double>{},
  Converter.magneticFieldIntensity: <dynamic, double>{},
  Converter.magneticFlux: <dynamic, double>{},
  Converter.magneticFluxDensity: <dynamic, double>{},
  Converter.mass: <dynamic, double>{},
  Converter.massFlow: <dynamic, double>{},
  Converter.massFraction: <dynamic, double>{},
  Converter.massMomentOfInertia: <dynamic, double>{},
  Converter.massPerArea: <dynamic, double>{},
  Converter.moleFraction: <dynamic, double>{},
  Converter.planeAngle: <dynamic, double>{},
  Converter.power: <dynamic, double>{},
  Converter.pressure: <dynamic, double>{},
  Converter.radioactivity: <dynamic, double>{},
  Converter.speed: <dynamic, double>{},
  Converter.time: <dynamic, double>{},
  Converter.torque: <dynamic, double>{},
  Converter.volume: <dynamic, double>{},
  Converter.volumeFlow: <dynamic, double>{},
  Converter.volumeFlowPerArea: <dynamic, double>{},
  Converter.volumePerArea: <dynamic, double>{},
  Converter.waterHardness: <dynamic, double>{},
};
