/// UTF-32 code point
const unicodeAngstrom = '\u00c5';
const unicodeMho = '\u2127';
const unicodeMicro = '\u03bc';
const unicodeOhm = '\u2126';
const unicodePartPerTenThousand = '\u2031';
const unicodePartPerThousand = '\u2030';
const unicodePlanck = '\u2133';
const unicodeSubscriptThree = '\u2083';
const unicodeSubscriptTwo = '\u2082';
const unicodeSubscriptZero = '\u2080';
const unicodeSuperscriptPlus = '\u207A';
const unicodeSuperscriptThree = '\u00b3';
const unicodeSuperscriptTwo = '\u00b2';
const unicodeSuperscriptZero = '\u00b0';
const unicodeTau = '\u03c4';
