/// Units of digital data
enum DataUnit {
  bit,
  byte,
  exaBit_binary,
  exaByte_binary,
  gigaBit_binary,
  gigaByte_binary,
  kiloBit_binary,
  kiloByte_binary,
  megaBit_binary,
  megaByte_binary,
  petaBit_binary,
  petaByte_binary,
  teraBit_binary,
  teraByte_binary,
  yottaBit_binary,
  yottaByte_binary,
  zettaBit_binary,
  zettaByte_binary,
}
