/// Units of electric current
enum ElectricCurrentUnit {
  abAmpere,
  ampere,
  attoAmpere,
  centiAmpere,
  decaAmpere,
  deciAmpere,
  exaAmpere,
  femtoAmpere,
  gigaAmpere,
  hectoAmpere,
  kiloAmpere,
  megaAmpere,
  microAmpere,
  milliAmpere,
  nanoAmpere,
  petaAmpere,
  picoAmpere,
  teraAmpere,
  yoctoAmpere,
  yottaAmpere,
  zeptoAmpere,
  zettaAmpere,
}
