/// Units of magnetic field intensity
enum MagneticFieldIntensityUnit {
  amperePerMetre,
  attoAmperePerMetre,
  centiAmperePerMetre,
  decaAmperePerMetre,
  deciAmperePerMetre,
  exaAmperePerMetre,
  femtoAmperePerMetre,
  gigaAmperePerMetre,
  hectoAmperePerMetre,
  kiloAmperePerMetre,
  megaAmperePerMetre,
  microAmperePerMetre,
  milliAmperePerMetre,
  nanoAmperePerMetre,
  oersted,
  petaAmperePerMetre,
  picoAmperePerMetre,
  teraAmperePerMetre,
  yoctoAmperePerMetre,
  yottaAmperePerMetre,
  zeptoAmperePerMetre,
  zettaAmperePerMetre,
}
