/// Units of mass per area
enum MassPerAreaUnit {
  kiloGramPerAcre,
  kiloGramPerHectare,
  kiloGramPerSquareMetre,
  kiloGramPerSquareMile,
  kiloGramPerSquareYard,
  longTonnePerAcre,
  longTonnePerHectare,
  longTonnePerSquareMetre,
  longTonnePerSquareMile,
  longTonnePerSquareYard,
  poundPerAcre,
  poundPerHectare,
  poundPerSquareMetre,
  poundPerSquareMile,
  poundPerSquareYard,
  shortTonnePerAcre,
  shortTonnePerHectare,
  shortTonnePerSquareMetre,
  shortTonnePerSquareMile,
  shortTonnePerSquareYard,
  tonnePerAcre,
  tonnePerHectare,
  tonnePerSquareMetre,
  tonnePerSquareMile,
  tonnePerSquareYard,
}
